export const FETCH_WEATHER_REQUEST:string = 'FETCH_WEATHER_REQUEST';
export const FETCH_WEATHER_SUCCESS:string = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILURE:string = 'FETCH_WEATHER_FAILURE';